version: "3.8"
services:
  # api:
  #   depends_on:
  #     - postgres
  #   build:
  #     dockerfile: Dockerfile 
  #     context: .
  #   environment:
  #     URL: postgres://user:password@postgres:5432/database
  #   ports: 
  #     - "8080:8080"
  postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
     - ./data/postgres:/data/postgres



