version: "3.8"
services:
  # api:
  #   build:
  #     dockerfile: Dockerfile 
  #     context: .
  #   depends_on:
  #     - postgres
  #   environment:
  #     URL: postgres://user:password@postgres:5432/database
  #     PORT: 2000
  #   ports: 
  #     - "2000:2000"
  postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres:/var/lib/postgres/database
volumes:
  postgres:



